{ Byte0_Tune.pas - generated by tools/tune_byte.py; do not edit by hand.
  Length-tunes byte 0: replaces the straight pieces listed below with the same pieces plus
  45-degree meander teeth, so every line reaches the byte's longest line. Nothing else changes.
  Run: open the PcbDoc > File > Run Script > Browse to Byte0_Tune.PrjScr > TuneByte > OK. Run once. }

Var
    Board : IPCB_Board;
    Done  : Integer;

Function IsClose(A, B : Double) : Boolean;
Begin
    Result := Abs(A - B) < 0.01;
End;

Procedure AddTrack(Net : IPCB_Net; Layer : TLayer; X1, Y1, X2, Y2 : Double);
Var
    T : IPCB_Track;
Begin
    T := PCBServer.PCBObjectFactory(eTrackObject, eNoDimension, eCreate_Default);
    T.Layer := Layer;
    T.Width := MMsToCoord(0.1);
    T.X1 := Board.XOrigin + MMsToCoord(X1);
    T.Y1 := Board.YOrigin + MMsToCoord(Y1);
    T.X2 := Board.XOrigin + MMsToCoord(X2);
    T.Y2 := Board.YOrigin + MMsToCoord(Y2);
    T.Net := Net;
    Board.AddPCBObject(T);
    PCBServer.SendMessageToRobots(Board.I_ObjectAddress, c_Broadcast, PCBM_BoardRegisteration, T.I_ObjectAddress);
End;

{ Find the track of NetName on Layer from (X1,Y1) to (X2,Y2) (either direction), remove it and
  return its net; Nil if it is not there }
Function TakeTrack(NetName : String; Layer : TLayer; X1, Y1, X2, Y2 : Double) : IPCB_Net;
Var
    Iter : IPCB_BoardIterator;
    T, F : IPCB_Track;
    AX, AY, BX, BY : Double;
Begin
    Result := Nil;
    F := Nil;
    Iter := Board.BoardIterator_Create;
    Iter.AddFilter_ObjectSet(MkSet(eTrackObject));
    Iter.AddFilter_LayerSet(MkSet(Layer));
    Iter.AddFilter_Method(eProcessAll);
    T := Iter.FirstPCBObject;
    While (T <> Nil) And (F = Nil) Do
    Begin
        If (T.Net <> Nil) And (T.Net.Name = NetName) Then
        Begin
            AX := CoordToMMs(T.X1 - Board.XOrigin); AY := CoordToMMs(T.Y1 - Board.YOrigin);
            BX := CoordToMMs(T.X2 - Board.XOrigin); BY := CoordToMMs(T.Y2 - Board.YOrigin);
            If (IsClose(AX, X1) And IsClose(AY, Y1) And IsClose(BX, X2) And IsClose(BY, Y2)) Or
               (IsClose(AX, X2) And IsClose(AY, Y2) And IsClose(BX, X1) And IsClose(BY, Y1)) Then F := T;
        End;
        T := Iter.NextPCBObject;
    End;
    Board.BoardIterator_Destroy(Iter);
    If F <> Nil Then
    Begin
        Result := F.Net;
        Board.RemovePCBObject(F);
    End;
End;

Procedure TuneByte;
Var
    N : IPCB_Net;
Begin
    Board := PCBServer.GetCurrentPCBBoard;
    If Board = Nil Then
    Begin
        ShowMessage('Open the DDR4 UDIMM PcbDoc first.');
        Exit;
    End;
    Done := 0;
    PCBServer.PreProcess;
    { R11 DM0 -> A7: +4.17 mm }
    N := TakeTrack('NetR11_1', eTopLayer, 8.4500, 5.3750, 8.4500, 9.7500);
    If N <> Nil Then
    Begin
        AddTrack(N, eTopLayer, 8.4500, 5.3750, 8.4500, 6.9950);
        AddTrack(N, eTopLayer, 8.4500, 6.9950, 8.3700, 7.0750);
        AddTrack(N, eTopLayer, 8.3700, 7.0750, 8.1100, 7.0750);
        AddTrack(N, eTopLayer, 8.1100, 7.0750, 8.0300, 7.1550);
        AddTrack(N, eTopLayer, 8.0300, 7.1550, 8.0300, 7.3950);
        AddTrack(N, eTopLayer, 8.0300, 7.3950, 8.1100, 7.4750);
        AddTrack(N, eTopLayer, 8.1100, 7.4750, 8.3700, 7.4750);
        AddTrack(N, eTopLayer, 8.3700, 7.4750, 8.4500, 7.5550);
        AddTrack(N, eTopLayer, 8.4500, 7.5550, 8.4500, 7.7550);
        AddTrack(N, eTopLayer, 8.4500, 7.7550, 8.3700, 7.8350);
        AddTrack(N, eTopLayer, 8.3700, 7.8350, 8.1100, 7.8350);
        AddTrack(N, eTopLayer, 8.1100, 7.8350, 8.0300, 7.9150);
        AddTrack(N, eTopLayer, 8.0300, 7.9150, 8.0300, 8.1550);
        AddTrack(N, eTopLayer, 8.0300, 8.1550, 8.1100, 8.2350);
        AddTrack(N, eTopLayer, 8.1100, 8.2350, 8.3700, 8.2350);
        AddTrack(N, eTopLayer, 8.3700, 8.2350, 8.4500, 8.3150);
        AddTrack(N, eTopLayer, 8.4500, 8.3150, 8.4500, 8.5150);
        AddTrack(N, eTopLayer, 8.4500, 8.5150, 8.3700, 8.5950);
        AddTrack(N, eTopLayer, 8.3700, 8.5950, 8.1100, 8.5950);
        AddTrack(N, eTopLayer, 8.1100, 8.5950, 8.0300, 8.6750);
        AddTrack(N, eTopLayer, 8.0300, 8.6750, 8.0300, 8.9150);
        AddTrack(N, eTopLayer, 8.0300, 8.9150, 8.1100, 8.9950);
        AddTrack(N, eTopLayer, 8.1100, 8.9950, 8.3700, 8.9950);
        AddTrack(N, eTopLayer, 8.3700, 8.9950, 8.4500, 9.0750);
        AddTrack(N, eTopLayer, 8.4500, 9.0750, 8.4500, 9.7500);
        Done := Done + 1;
    End;
    N := TakeTrack('DM0', eTopLayer, 8.4500, 1.6750, 8.4500, 4.6250);
    If N <> Nil Then
    Begin
        AddTrack(N, eTopLayer, 8.4500, 1.6750, 8.4500, 3.2950);
        AddTrack(N, eTopLayer, 8.4500, 3.2950, 8.3700, 3.3750);
        AddTrack(N, eTopLayer, 8.3700, 3.3750, 7.3300, 3.3750);
        AddTrack(N, eTopLayer, 7.3300, 3.3750, 7.2500, 3.4550);
        AddTrack(N, eTopLayer, 7.2500, 3.4550, 7.2500, 3.6950);
        AddTrack(N, eTopLayer, 7.2500, 3.6950, 7.3300, 3.7750);
        AddTrack(N, eTopLayer, 7.3300, 3.7750, 8.3700, 3.7750);
        AddTrack(N, eTopLayer, 8.3700, 3.7750, 8.4500, 3.8550);
        AddTrack(N, eTopLayer, 8.4500, 3.8550, 8.4500, 4.6250);
        Done := Done + 1;
    End;
    { R3 DQ1 -> B7: +9.11 mm }
    N := TakeTrack('DQ1', eBottomLayer, 7.6000, 1.6750, 7.6000, 6.3500);
    If N <> Nil Then
    Begin
        AddTrack(N, eBottomLayer, 7.6000, 1.6750, 7.6000, 3.2950);
        AddTrack(N, eBottomLayer, 7.6000, 3.2950, 7.5200, 3.3750);
        AddTrack(N, eBottomLayer, 7.5200, 3.3750, 6.4800, 3.3750);
        AddTrack(N, eBottomLayer, 6.4800, 3.3750, 6.4000, 3.4550);
        AddTrack(N, eBottomLayer, 6.4000, 3.4550, 6.4000, 3.6950);
        AddTrack(N, eBottomLayer, 6.4000, 3.6950, 6.4800, 3.7750);
        AddTrack(N, eBottomLayer, 6.4800, 3.7750, 7.5200, 3.7750);
        AddTrack(N, eBottomLayer, 7.5200, 3.7750, 7.6000, 3.8550);
        AddTrack(N, eBottomLayer, 7.6000, 3.8550, 7.6000, 4.0550);
        AddTrack(N, eBottomLayer, 7.6000, 4.0550, 7.5200, 4.1350);
        AddTrack(N, eBottomLayer, 7.5200, 4.1350, 6.4800, 4.1350);
        AddTrack(N, eBottomLayer, 6.4800, 4.1350, 6.4000, 4.2150);
        AddTrack(N, eBottomLayer, 6.4000, 4.2150, 6.4000, 4.4550);
        AddTrack(N, eBottomLayer, 6.4000, 4.4550, 6.4800, 4.5350);
        AddTrack(N, eBottomLayer, 6.4800, 4.5350, 7.5200, 4.5350);
        AddTrack(N, eBottomLayer, 7.5200, 4.5350, 7.6000, 4.6150);
        AddTrack(N, eBottomLayer, 7.6000, 4.6150, 7.6000, 4.8150);
        AddTrack(N, eBottomLayer, 7.6000, 4.8150, 7.5200, 4.8950);
        AddTrack(N, eBottomLayer, 7.5200, 4.8950, 6.4800, 4.8950);
        AddTrack(N, eBottomLayer, 6.4800, 4.8950, 6.4000, 4.9750);
        AddTrack(N, eBottomLayer, 6.4000, 4.9750, 6.4000, 5.2150);
        AddTrack(N, eBottomLayer, 6.4000, 5.2150, 6.4800, 5.2950);
        AddTrack(N, eBottomLayer, 6.4800, 5.2950, 7.5200, 5.2950);
        AddTrack(N, eBottomLayer, 7.5200, 5.2950, 7.6000, 5.3750);
        AddTrack(N, eBottomLayer, 7.6000, 5.3750, 7.6000, 5.5750);
        AddTrack(N, eBottomLayer, 7.6000, 5.5750, 7.5200, 5.6550);
        AddTrack(N, eBottomLayer, 7.5200, 5.6550, 6.4800, 5.6550);
        AddTrack(N, eBottomLayer, 6.4800, 5.6550, 6.4000, 5.7350);
        AddTrack(N, eBottomLayer, 6.4000, 5.7350, 6.4000, 5.9750);
        AddTrack(N, eBottomLayer, 6.4000, 5.9750, 6.4800, 6.0550);
        AddTrack(N, eBottomLayer, 6.4800, 6.0550, 7.5200, 6.0550);
        AddTrack(N, eBottomLayer, 7.5200, 6.0550, 7.6000, 6.1350);
        AddTrack(N, eBottomLayer, 7.6000, 6.1350, 7.6000, 6.3500);
        Done := Done + 1;
    End;
    N := TakeTrack('DQ1', eTopLayer, 7.6000, 6.3500, 7.6000, 7.1250);
    If N <> Nil Then
    Begin
        AddTrack(N, eTopLayer, 7.6000, 6.3500, 7.6000, 6.4500);
        AddTrack(N, eTopLayer, 7.6000, 6.4500, 7.5200, 6.5300);
        AddTrack(N, eTopLayer, 7.5200, 6.5300, 7.4564, 6.5300);
        AddTrack(N, eTopLayer, 7.4564, 6.5300, 7.3764, 6.6100);
        AddTrack(N, eTopLayer, 7.3764, 6.6100, 7.3764, 6.8500);
        AddTrack(N, eTopLayer, 7.3764, 6.8500, 7.4564, 6.9300);
        AddTrack(N, eTopLayer, 7.4564, 6.9300, 7.5200, 6.9300);
        AddTrack(N, eTopLayer, 7.5200, 6.9300, 7.6000, 7.0100);
        AddTrack(N, eTopLayer, 7.6000, 7.0100, 7.6000, 7.1250);
        Done := Done + 1;
    End;
    { R4 DQ2 -> D3: +7.04 mm }
    N := TakeTrack('NetR4_1', eTopLayer, 12.7000, 5.3750, 12.7000, 9.1500);
    If N <> Nil Then
    Begin
        AddTrack(N, eTopLayer, 12.7000, 5.3750, 12.7000, 5.4750);
        AddTrack(N, eTopLayer, 12.7000, 5.4750, 12.6200, 5.5550);
        AddTrack(N, eTopLayer, 12.6200, 5.5550, 12.3600, 5.5550);
        AddTrack(N, eTopLayer, 12.3600, 5.5550, 12.2800, 5.6350);
        AddTrack(N, eTopLayer, 12.2800, 5.6350, 12.2800, 5.8750);
        AddTrack(N, eTopLayer, 12.2800, 5.8750, 12.3600, 5.9550);
        AddTrack(N, eTopLayer, 12.3600, 5.9550, 12.6200, 5.9550);
        AddTrack(N, eTopLayer, 12.6200, 5.9550, 12.7000, 6.0350);
        AddTrack(N, eTopLayer, 12.7000, 6.0350, 12.7000, 6.2350);
        AddTrack(N, eTopLayer, 12.7000, 6.2350, 12.6200, 6.3150);
        AddTrack(N, eTopLayer, 12.6200, 6.3150, 12.3600, 6.3150);
        AddTrack(N, eTopLayer, 12.3600, 6.3150, 12.2800, 6.3950);
        AddTrack(N, eTopLayer, 12.2800, 6.3950, 12.2800, 6.6350);
        AddTrack(N, eTopLayer, 12.2800, 6.6350, 12.3600, 6.7150);
        AddTrack(N, eTopLayer, 12.3600, 6.7150, 12.6200, 6.7150);
        AddTrack(N, eTopLayer, 12.6200, 6.7150, 12.7000, 6.7950);
        AddTrack(N, eTopLayer, 12.7000, 6.7950, 12.7000, 6.9950);
        AddTrack(N, eTopLayer, 12.7000, 6.9950, 12.6200, 7.0750);
        AddTrack(N, eTopLayer, 12.6200, 7.0750, 12.3600, 7.0750);
        AddTrack(N, eTopLayer, 12.3600, 7.0750, 12.2800, 7.1550);
        AddTrack(N, eTopLayer, 12.2800, 7.1550, 12.2800, 7.3950);
        AddTrack(N, eTopLayer, 12.2800, 7.3950, 12.3600, 7.4750);
        AddTrack(N, eTopLayer, 12.3600, 7.4750, 12.6200, 7.4750);
        AddTrack(N, eTopLayer, 12.6200, 7.4750, 12.7000, 7.5550);
        AddTrack(N, eTopLayer, 12.7000, 7.5550, 12.7000, 7.7550);
        AddTrack(N, eTopLayer, 12.7000, 7.7550, 12.6200, 7.8350);
        AddTrack(N, eTopLayer, 12.6200, 7.8350, 12.3600, 7.8350);
        AddTrack(N, eTopLayer, 12.3600, 7.8350, 12.2800, 7.9150);
        AddTrack(N, eTopLayer, 12.2800, 7.9150, 12.2800, 8.1550);
        AddTrack(N, eTopLayer, 12.2800, 8.1550, 12.3600, 8.2350);
        AddTrack(N, eTopLayer, 12.3600, 8.2350, 12.6200, 8.2350);
        AddTrack(N, eTopLayer, 12.6200, 8.2350, 12.7000, 8.3150);
        AddTrack(N, eTopLayer, 12.7000, 8.3150, 12.7000, 9.1500);
        Done := Done + 1;
    End;
    N := TakeTrack('DQ2', eTopLayer, 12.7000, 1.6750, 12.7000, 4.6250);
    If N <> Nil Then
    Begin
        AddTrack(N, eTopLayer, 12.7000, 1.6750, 12.7000, 3.2950);
        AddTrack(N, eTopLayer, 12.7000, 3.2950, 12.6200, 3.3750);
        AddTrack(N, eTopLayer, 12.6200, 3.3750, 11.5800, 3.3750);
        AddTrack(N, eTopLayer, 11.5800, 3.3750, 11.5000, 3.4550);
        AddTrack(N, eTopLayer, 11.5000, 3.4550, 11.5000, 3.6950);
        AddTrack(N, eTopLayer, 11.5000, 3.6950, 11.5800, 3.7750);
        AddTrack(N, eTopLayer, 11.5800, 3.7750, 12.6200, 3.7750);
        AddTrack(N, eTopLayer, 12.6200, 3.7750, 12.7000, 3.8550);
        AddTrack(N, eTopLayer, 12.7000, 3.8550, 12.7000, 4.6250);
        Done := Done + 1;
    End;
    N := TakeTrack('NetR4_1', eMidLayer2, 12.3750, 9.4750, 12.3750, 10.9300);
    If N <> Nil Then
    Begin
        AddTrack(N, eMidLayer2, 12.3750, 9.4750, 12.3750, 9.5750);
        AddTrack(N, eMidLayer2, 12.3750, 9.5750, 12.2950, 9.6550);
        AddTrack(N, eMidLayer2, 12.2950, 9.6550, 11.2550, 9.6550);
        AddTrack(N, eMidLayer2, 11.2550, 9.6550, 11.1750, 9.7350);
        AddTrack(N, eMidLayer2, 11.1750, 9.7350, 11.1750, 9.9750);
        AddTrack(N, eMidLayer2, 11.1750, 9.9750, 11.2550, 10.0550);
        AddTrack(N, eMidLayer2, 11.2550, 10.0550, 12.2950, 10.0550);
        AddTrack(N, eMidLayer2, 12.2950, 10.0550, 12.3750, 10.1350);
        AddTrack(N, eMidLayer2, 12.3750, 10.1350, 12.3750, 10.9300);
        Done := Done + 1;
    End;
    { R12 DQ5 -> D8: +7.20 mm }
    N := TakeTrack('DQ5', eBottomLayer, 5.9000, 1.6750, 5.9000, 6.4750);
    If N <> Nil Then
    Begin
        AddTrack(N, eBottomLayer, 5.9000, 1.6750, 5.9000, 3.2950);
        AddTrack(N, eBottomLayer, 5.9000, 3.2950, 5.8200, 3.3750);
        AddTrack(N, eBottomLayer, 5.8200, 3.3750, 4.7800, 3.3750);
        AddTrack(N, eBottomLayer, 4.7800, 3.3750, 4.7000, 3.4550);
        AddTrack(N, eBottomLayer, 4.7000, 3.4550, 4.7000, 3.6950);
        AddTrack(N, eBottomLayer, 4.7000, 3.6950, 4.7800, 3.7750);
        AddTrack(N, eBottomLayer, 4.7800, 3.7750, 5.8200, 3.7750);
        AddTrack(N, eBottomLayer, 5.8200, 3.7750, 5.9000, 3.8550);
        AddTrack(N, eBottomLayer, 5.9000, 3.8550, 5.9000, 4.0550);
        AddTrack(N, eBottomLayer, 5.9000, 4.0550, 5.8200, 4.1350);
        AddTrack(N, eBottomLayer, 5.8200, 4.1350, 4.7800, 4.1350);
        AddTrack(N, eBottomLayer, 4.7800, 4.1350, 4.7000, 4.2150);
        AddTrack(N, eBottomLayer, 4.7000, 4.2150, 4.7000, 4.4550);
        AddTrack(N, eBottomLayer, 4.7000, 4.4550, 4.7800, 4.5350);
        AddTrack(N, eBottomLayer, 4.7800, 4.5350, 5.8200, 4.5350);
        AddTrack(N, eBottomLayer, 5.8200, 4.5350, 5.9000, 4.6150);
        AddTrack(N, eBottomLayer, 5.9000, 4.6150, 5.9000, 4.8150);
        AddTrack(N, eBottomLayer, 5.9000, 4.8150, 5.8200, 4.8950);
        AddTrack(N, eBottomLayer, 5.8200, 4.8950, 4.7800, 4.8950);
        AddTrack(N, eBottomLayer, 4.7800, 4.8950, 4.7000, 4.9750);
        AddTrack(N, eBottomLayer, 4.7000, 4.9750, 4.7000, 5.2150);
        AddTrack(N, eBottomLayer, 4.7000, 5.2150, 4.7800, 5.2950);
        AddTrack(N, eBottomLayer, 4.7800, 5.2950, 5.8200, 5.2950);
        AddTrack(N, eBottomLayer, 5.8200, 5.2950, 5.9000, 5.3750);
        AddTrack(N, eBottomLayer, 5.9000, 5.3750, 5.9000, 5.5750);
        AddTrack(N, eBottomLayer, 5.9000, 5.5750, 5.8200, 5.6550);
        AddTrack(N, eBottomLayer, 5.8200, 5.6550, 5.6055, 5.6550);
        AddTrack(N, eBottomLayer, 5.6055, 5.6550, 5.5255, 5.7350);
        AddTrack(N, eBottomLayer, 5.5255, 5.7350, 5.5255, 5.9750);
        AddTrack(N, eBottomLayer, 5.5255, 5.9750, 5.6055, 6.0550);
        AddTrack(N, eBottomLayer, 5.6055, 6.0550, 5.8200, 6.0550);
        AddTrack(N, eBottomLayer, 5.8200, 6.0550, 5.9000, 6.1350);
        AddTrack(N, eBottomLayer, 5.9000, 6.1350, 5.9000, 6.4750);
        Done := Done + 1;
    End;
    { R10 DQS0_C -> B3: +6.34 mm }
    N := TakeTrack('DQS0_C', eBottomLayer, 9.3000, 1.6750, 9.3000, 6.0300);
    If N <> Nil Then
    Begin
        AddTrack(N, eBottomLayer, 9.3000, 1.6750, 9.3000, 3.2950);
        AddTrack(N, eBottomLayer, 9.3000, 3.2950, 9.2200, 3.3750);
        AddTrack(N, eBottomLayer, 9.2200, 3.3750, 8.1800, 3.3750);
        AddTrack(N, eBottomLayer, 8.1800, 3.3750, 8.1000, 3.4550);
        AddTrack(N, eBottomLayer, 8.1000, 3.4550, 8.1000, 3.6950);
        AddTrack(N, eBottomLayer, 8.1000, 3.6950, 8.1800, 3.7750);
        AddTrack(N, eBottomLayer, 8.1800, 3.7750, 9.2200, 3.7750);
        AddTrack(N, eBottomLayer, 9.2200, 3.7750, 9.3000, 3.8550);
        AddTrack(N, eBottomLayer, 9.3000, 3.8550, 9.3000, 4.0550);
        AddTrack(N, eBottomLayer, 9.3000, 4.0550, 9.2200, 4.1350);
        AddTrack(N, eBottomLayer, 9.2200, 4.1350, 8.1800, 4.1350);
        AddTrack(N, eBottomLayer, 8.1800, 4.1350, 8.1000, 4.2150);
        AddTrack(N, eBottomLayer, 8.1000, 4.2150, 8.1000, 4.4550);
        AddTrack(N, eBottomLayer, 8.1000, 4.4550, 8.1800, 4.5350);
        AddTrack(N, eBottomLayer, 8.1800, 4.5350, 9.2200, 4.5350);
        AddTrack(N, eBottomLayer, 9.2200, 4.5350, 9.3000, 4.6150);
        AddTrack(N, eBottomLayer, 9.3000, 4.6150, 9.3000, 4.8150);
        AddTrack(N, eBottomLayer, 9.3000, 4.8150, 9.2200, 4.8950);
        AddTrack(N, eBottomLayer, 9.2200, 4.8950, 8.3268, 4.8950);
        AddTrack(N, eBottomLayer, 8.3268, 4.8950, 8.2468, 4.9750);
        AddTrack(N, eBottomLayer, 8.2468, 4.9750, 8.2468, 5.2150);
        AddTrack(N, eBottomLayer, 8.2468, 5.2150, 8.3268, 5.2950);
        AddTrack(N, eBottomLayer, 8.3268, 5.2950, 9.2200, 5.2950);
        AddTrack(N, eBottomLayer, 9.2200, 5.2950, 9.3000, 5.3750);
        AddTrack(N, eBottomLayer, 9.3000, 5.3750, 9.3000, 6.0300);
        Done := Done + 1;
    End;
    { R2 DQ0 -> C2: +6.19 mm }
    N := TakeTrack('NetR2_1', eBottomLayer, 8.0750, 6.1500, 12.1000, 10.1750);
    If N <> Nil Then
    Begin
        AddTrack(N, eBottomLayer, 8.0750, 6.1500, 8.1457, 6.2207);
        AddTrack(N, eBottomLayer, 8.1457, 6.2207, 8.1457, 6.3338);
        AddTrack(N, eBottomLayer, 8.1457, 6.3338, 7.4103, 7.0692);
        AddTrack(N, eBottomLayer, 7.4103, 7.0692, 7.4103, 7.1824);
        AddTrack(N, eBottomLayer, 7.4103, 7.1824, 7.5800, 7.3521);
        AddTrack(N, eBottomLayer, 7.5800, 7.3521, 7.6932, 7.3521);
        AddTrack(N, eBottomLayer, 7.6932, 7.3521, 8.4286, 6.6167);
        AddTrack(N, eBottomLayer, 8.4286, 6.6167, 8.5417, 6.6167);
        AddTrack(N, eBottomLayer, 8.5417, 6.6167, 8.6831, 6.7581);
        AddTrack(N, eBottomLayer, 8.6831, 6.7581, 8.6831, 6.8712);
        AddTrack(N, eBottomLayer, 8.6831, 6.8712, 7.9477, 7.6066);
        AddTrack(N, eBottomLayer, 7.9477, 7.6066, 7.9477, 7.7198);
        AddTrack(N, eBottomLayer, 7.9477, 7.7198, 8.1174, 7.8895);
        AddTrack(N, eBottomLayer, 8.1174, 7.8895, 8.2306, 7.8895);
        AddTrack(N, eBottomLayer, 8.2306, 7.8895, 8.9660, 7.1541);
        AddTrack(N, eBottomLayer, 8.9660, 7.1541, 9.0791, 7.1541);
        AddTrack(N, eBottomLayer, 9.0791, 7.1541, 9.2205, 7.2955);
        AddTrack(N, eBottomLayer, 9.2205, 7.2955, 9.2205, 7.4087);
        AddTrack(N, eBottomLayer, 9.2205, 7.4087, 8.6449, 7.9843);
        AddTrack(N, eBottomLayer, 8.6449, 7.9843, 8.6449, 8.0974);
        AddTrack(N, eBottomLayer, 8.6449, 8.0974, 8.8146, 8.2672);
        AddTrack(N, eBottomLayer, 8.8146, 8.2672, 8.9277, 8.2672);
        AddTrack(N, eBottomLayer, 8.9277, 8.2672, 9.5034, 7.6915);
        AddTrack(N, eBottomLayer, 9.5034, 7.6915, 9.6165, 7.6915);
        AddTrack(N, eBottomLayer, 9.6165, 7.6915, 12.1000, 10.1750);
        Done := Done + 1;
    End;
    { R9 DQS0_T -> C3: +6.01 mm }
    N := TakeTrack('DQS0_T', eBottomLayer, 10.1500, 1.6750, 10.1500, 6.1000);
    If N <> Nil Then
    Begin
        AddTrack(N, eBottomLayer, 10.1500, 1.6750, 10.1500, 3.2950);
        AddTrack(N, eBottomLayer, 10.1500, 3.2950, 10.2300, 3.3750);
        AddTrack(N, eBottomLayer, 10.2300, 3.3750, 11.2700, 3.3750);
        AddTrack(N, eBottomLayer, 11.2700, 3.3750, 11.3500, 3.4550);
        AddTrack(N, eBottomLayer, 11.3500, 3.4550, 11.3500, 3.6950);
        AddTrack(N, eBottomLayer, 11.3500, 3.6950, 11.2700, 3.7750);
        AddTrack(N, eBottomLayer, 11.2700, 3.7750, 10.2300, 3.7750);
        AddTrack(N, eBottomLayer, 10.2300, 3.7750, 10.1500, 3.8550);
        AddTrack(N, eBottomLayer, 10.1500, 3.8550, 10.1500, 4.0550);
        AddTrack(N, eBottomLayer, 10.1500, 4.0550, 10.2300, 4.1350);
        AddTrack(N, eBottomLayer, 10.2300, 4.1350, 11.2700, 4.1350);
        AddTrack(N, eBottomLayer, 11.2700, 4.1350, 11.3500, 4.2150);
        AddTrack(N, eBottomLayer, 11.3500, 4.2150, 11.3500, 4.4550);
        AddTrack(N, eBottomLayer, 11.3500, 4.4550, 11.2700, 4.5350);
        AddTrack(N, eBottomLayer, 11.2700, 4.5350, 10.2300, 4.5350);
        AddTrack(N, eBottomLayer, 10.2300, 4.5350, 10.1500, 4.6150);
        AddTrack(N, eBottomLayer, 10.1500, 4.6150, 10.1500, 4.8150);
        AddTrack(N, eBottomLayer, 10.1500, 4.8150, 10.2300, 4.8950);
        AddTrack(N, eBottomLayer, 10.2300, 4.8950, 10.9575, 4.8950);
        AddTrack(N, eBottomLayer, 10.9575, 4.8950, 11.0375, 4.9750);
        AddTrack(N, eBottomLayer, 11.0375, 4.9750, 11.0375, 5.2150);
        AddTrack(N, eBottomLayer, 11.0375, 5.2150, 10.9575, 5.2950);
        AddTrack(N, eBottomLayer, 10.9575, 5.2950, 10.2300, 5.2950);
        AddTrack(N, eBottomLayer, 10.2300, 5.2950, 10.1500, 5.3750);
        AddTrack(N, eBottomLayer, 10.1500, 5.3750, 10.1500, 6.1000);
        Done := Done + 1;
    End;
    { R6 DQ4 -> D2: +4.59 mm }
    N := TakeTrack('NetR6_1', eBottomLayer, 5.1250, 6.2250, 11.0250, 12.1250);
    If N <> Nil Then
    Begin
        AddTrack(N, eBottomLayer, 5.1250, 6.2250, 5.1957, 6.2957);
        AddTrack(N, eBottomLayer, 5.1957, 6.2957, 5.1957, 6.4088);
        AddTrack(N, eBottomLayer, 5.1957, 6.4088, 4.6017, 7.0028);
        AddTrack(N, eBottomLayer, 4.6017, 7.0028, 4.6017, 7.1160);
        AddTrack(N, eBottomLayer, 4.6017, 7.1160, 4.7714, 7.2857);
        AddTrack(N, eBottomLayer, 4.7714, 7.2857, 4.8846, 7.2857);
        AddTrack(N, eBottomLayer, 4.8846, 7.2857, 5.4786, 6.6917);
        AddTrack(N, eBottomLayer, 5.4786, 6.6917, 5.5917, 6.6917);
        AddTrack(N, eBottomLayer, 5.5917, 6.6917, 5.7331, 6.8331);
        AddTrack(N, eBottomLayer, 5.7331, 6.8331, 5.7331, 6.9462);
        AddTrack(N, eBottomLayer, 5.7331, 6.9462, 5.1391, 7.5402);
        AddTrack(N, eBottomLayer, 5.1391, 7.5402, 5.1391, 7.6534);
        AddTrack(N, eBottomLayer, 5.1391, 7.6534, 5.3088, 7.8231);
        AddTrack(N, eBottomLayer, 5.3088, 7.8231, 5.4220, 7.8231);
        AddTrack(N, eBottomLayer, 5.4220, 7.8231, 6.0160, 7.2291);
        AddTrack(N, eBottomLayer, 6.0160, 7.2291, 6.1291, 7.2291);
        AddTrack(N, eBottomLayer, 6.1291, 7.2291, 6.2705, 7.3705);
        AddTrack(N, eBottomLayer, 6.2705, 7.3705, 6.2705, 7.4836);
        AddTrack(N, eBottomLayer, 6.2705, 7.4836, 5.9749, 7.7793);
        AddTrack(N, eBottomLayer, 5.9749, 7.7793, 5.9749, 7.8924);
        AddTrack(N, eBottomLayer, 5.9749, 7.8924, 6.1446, 8.0621);
        AddTrack(N, eBottomLayer, 6.1446, 8.0621, 6.2577, 8.0621);
        AddTrack(N, eBottomLayer, 6.2577, 8.0621, 6.5534, 7.7665);
        AddTrack(N, eBottomLayer, 6.5534, 7.7665, 6.6665, 7.7665);
        AddTrack(N, eBottomLayer, 6.6665, 7.7665, 11.0250, 12.1250);
        Done := Done + 1;
    End;
    { R7 DQ6 -> E3: +3.56 mm }
    N := TakeTrack('NetR7_1', eTopLayer, 11.0000, 5.3750, 11.0000, 8.7450);
    If N <> Nil Then
    Begin
        AddTrack(N, eTopLayer, 11.0000, 5.3750, 11.0000, 5.4750);
        AddTrack(N, eTopLayer, 11.0000, 5.4750, 11.0800, 5.5550);
        AddTrack(N, eTopLayer, 11.0800, 5.5550, 11.3400, 5.5550);
        AddTrack(N, eTopLayer, 11.3400, 5.5550, 11.4200, 5.6350);
        AddTrack(N, eTopLayer, 11.4200, 5.6350, 11.4200, 5.8750);
        AddTrack(N, eTopLayer, 11.4200, 5.8750, 11.3400, 5.9550);
        AddTrack(N, eTopLayer, 11.3400, 5.9550, 11.0800, 5.9550);
        AddTrack(N, eTopLayer, 11.0800, 5.9550, 11.0000, 6.0350);
        AddTrack(N, eTopLayer, 11.0000, 6.0350, 11.0000, 6.2350);
        AddTrack(N, eTopLayer, 11.0000, 6.2350, 11.0800, 6.3150);
        AddTrack(N, eTopLayer, 11.0800, 6.3150, 11.3400, 6.3150);
        AddTrack(N, eTopLayer, 11.3400, 6.3150, 11.4200, 6.3950);
        AddTrack(N, eTopLayer, 11.4200, 6.3950, 11.4200, 6.6350);
        AddTrack(N, eTopLayer, 11.4200, 6.6350, 11.3400, 6.7150);
        AddTrack(N, eTopLayer, 11.3400, 6.7150, 11.0800, 6.7150);
        AddTrack(N, eTopLayer, 11.0800, 6.7150, 11.0000, 6.7950);
        AddTrack(N, eTopLayer, 11.0000, 6.7950, 11.0000, 6.9950);
        AddTrack(N, eTopLayer, 11.0000, 6.9950, 11.0800, 7.0750);
        AddTrack(N, eTopLayer, 11.0800, 7.0750, 11.3400, 7.0750);
        AddTrack(N, eTopLayer, 11.3400, 7.0750, 11.4200, 7.1550);
        AddTrack(N, eTopLayer, 11.4200, 7.1550, 11.4200, 7.3950);
        AddTrack(N, eTopLayer, 11.4200, 7.3950, 11.3400, 7.4750);
        AddTrack(N, eTopLayer, 11.3400, 7.4750, 11.0800, 7.4750);
        AddTrack(N, eTopLayer, 11.0800, 7.4750, 11.0000, 7.5550);
        AddTrack(N, eTopLayer, 11.0000, 7.5550, 11.0000, 7.7550);
        AddTrack(N, eTopLayer, 11.0000, 7.7550, 11.0800, 7.8350);
        AddTrack(N, eTopLayer, 11.0800, 7.8350, 11.3400, 7.8350);
        AddTrack(N, eTopLayer, 11.3400, 7.8350, 11.4200, 7.9150);
        AddTrack(N, eTopLayer, 11.4200, 7.9150, 11.4200, 8.1550);
        AddTrack(N, eTopLayer, 11.4200, 8.1550, 11.3400, 8.2350);
        AddTrack(N, eTopLayer, 11.3400, 8.2350, 11.0800, 8.2350);
        AddTrack(N, eTopLayer, 11.0800, 8.2350, 11.0000, 8.3150);
        AddTrack(N, eTopLayer, 11.0000, 8.3150, 11.0000, 8.7450);
        Done := Done + 1;
    End;
    N := TakeTrack('DQ6', eTopLayer, 11.0000, 1.6750, 11.0000, 4.6250);
    If N <> Nil Then
    Begin
        AddTrack(N, eTopLayer, 11.0000, 1.6750, 11.0000, 3.2950);
        AddTrack(N, eTopLayer, 11.0000, 3.2950, 10.9200, 3.3750);
        AddTrack(N, eTopLayer, 10.9200, 3.3750, 10.5129, 3.3750);
        AddTrack(N, eTopLayer, 10.5129, 3.3750, 10.4329, 3.4550);
        AddTrack(N, eTopLayer, 10.4329, 3.4550, 10.4329, 3.6950);
        AddTrack(N, eTopLayer, 10.4329, 3.6950, 10.5129, 3.7750);
        AddTrack(N, eTopLayer, 10.5129, 3.7750, 10.9200, 3.7750);
        AddTrack(N, eTopLayer, 10.9200, 3.7750, 11.0000, 3.8550);
        AddTrack(N, eTopLayer, 11.0000, 3.8550, 11.0000, 4.6250);
        Done := Done + 1;
    End;
    { R5 DQ3 -> D7: +1.91 mm }
    N := TakeTrack('DQ3', eBottomLayer, 13.5500, 1.6750, 13.5500, 6.4000);
    If N <> Nil Then
    Begin
        AddTrack(N, eBottomLayer, 13.5500, 1.6750, 13.5500, 3.2950);
        AddTrack(N, eBottomLayer, 13.5500, 3.2950, 13.4700, 3.3750);
        AddTrack(N, eBottomLayer, 13.4700, 3.3750, 12.5837, 3.3750);
        AddTrack(N, eBottomLayer, 12.5837, 3.3750, 12.5037, 3.4550);
        AddTrack(N, eBottomLayer, 12.5037, 3.4550, 12.5037, 3.6950);
        AddTrack(N, eBottomLayer, 12.5037, 3.6950, 12.5837, 3.7750);
        AddTrack(N, eBottomLayer, 12.5837, 3.7750, 13.4700, 3.7750);
        AddTrack(N, eBottomLayer, 13.4700, 3.7750, 13.5500, 3.8550);
        AddTrack(N, eBottomLayer, 13.5500, 3.8550, 13.5500, 6.4000);
        Done := Done + 1;
    End;
    PCBServer.PostProcess;
    Board.ViewManager_FullUpdate;
    ShowMessage('Tuned ' + IntToStr(Done) + ' pieces in byte 0. Save the PcbDoc.');
End;
