{ DDR4_Placement.pas - generated by tools/gen_placement.py; do not edit by hand.
  Places only the 88 x 15 ohm data resistors at the JEDEC-derived position in
  hardware/placement.csv (x, y in mm from the board origin, rotation in degrees).
  Run: open the PcbDoc > File > Run Script > Browse to DDR4_DataResistors.PrjScr > PlaceComponents > OK.
  It only moves and rotates existing parts, so running it again is safe. }

Var
    Board  : IPCB_Board;
    Placed : Integer;
    Missed : String;

Procedure Place(Des : String; X, Y, Rot : Double);
Var
    Iter : IPCB_BoardIterator;
    C    : IPCB_Component;
    Done : Boolean;
Begin
    Done := False;
    Iter := Board.BoardIterator_Create;
    Iter.AddFilter_ObjectSet(MkSet(eComponentObject));
    Iter.AddFilter_LayerSet(AllLayers);
    Iter.AddFilter_Method(eProcessAll);
    C := Iter.FirstPCBObject;
    While (C <> Nil) And (Not Done) Do
    Begin
        If C.Name.Text = Des Then
        Begin
            PCBServer.SendMessageToRobots(C.I_ObjectAddress, c_Broadcast, PCBM_BeginModify, c_NoEventData);
            C.Rotation := Rot;
            C.MoveToXY(Board.XOrigin + MMsToCoord(X), Board.YOrigin + MMsToCoord(Y));
            PCBServer.SendMessageToRobots(C.I_ObjectAddress, c_Broadcast, PCBM_EndModify, c_NoEventData);
            Placed := Placed + 1;
            Done := True;
        End;
        C := Iter.NextPCBObject;
    End;
    Board.BoardIterator_Destroy(Iter);
    If Not Done Then Missed := Missed + Des + ' ';
End;

Procedure PlaceComponents;
Begin
    Board := PCBServer.GetCurrentPCBBoard;
    If Board = Nil Then
    Begin
        ShowMessage('Open the DDR4 UDIMM PcbDoc first.');
        Exit;
    End;
    Placed := 0;
    Missed := '';
    PCBServer.PreProcess;
    Place('R2', 6.750, 5.000, 270);
    Place('R4', 12.700, 5.000, 270);
    Place('R6', 5.050, 5.000, 270);
    Place('R7', 11.000, 5.000, 270);
    Place('R11', 8.450, 5.000, 270);
    Place('R12', 5.900, 7.500, 270);
    Place('R3', 7.600, 7.500, 270);
    Place('R10', 9.075, 7.500, 270);
    Place('R9', 10.375, 7.500, 270);
    Place('R8', 11.850, 7.500, 270);
    Place('R5', 13.550, 7.500, 270);
    Place('R14', 16.100, 5.000, 270);
    Place('R16', 22.050, 5.000, 270);
    Place('R18', 14.400, 5.000, 270);
    Place('R19', 20.350, 5.000, 270);
    Place('R23', 17.800, 5.000, 270);
    Place('R24', 15.250, 7.500, 270);
    Place('R15', 16.950, 7.500, 270);
    Place('R22', 18.425, 7.500, 270);
    Place('R21', 19.725, 7.500, 270);
    Place('R20', 21.200, 7.500, 270);
    Place('R17', 22.900, 7.500, 270);
    Place('R26', 25.450, 5.000, 270);
    Place('R28', 31.400, 5.000, 270);
    Place('R30', 23.750, 5.000, 270);
    Place('R31', 29.700, 5.000, 270);
    Place('R35', 27.150, 5.000, 270);
    Place('R36', 24.600, 7.500, 270);
    Place('R27', 26.300, 7.500, 270);
    Place('R34', 27.775, 7.500, 270);
    Place('R33', 29.075, 7.500, 270);
    Place('R32', 30.550, 7.500, 270);
    Place('R29', 32.250, 7.500, 270);
    Place('R38', 34.800, 5.000, 270);
    Place('R40', 40.750, 5.000, 270);
    Place('R42', 33.100, 5.000, 270);
    Place('R43', 39.050, 5.000, 270);
    Place('R47', 36.500, 5.000, 270);
    Place('R48', 33.950, 7.500, 270);
    Place('R39', 35.650, 7.500, 270);
    Place('R46', 37.125, 7.500, 270);
    Place('R45', 38.425, 7.500, 270);
    Place('R44', 39.900, 7.500, 270);
    Place('R41', 41.600, 7.500, 270);
    Place('R50', 90.050, 5.000, 270);
    Place('R52', 96.000, 5.000, 270);
    Place('R54', 88.350, 5.000, 270);
    Place('R55', 94.300, 5.000, 270);
    Place('R59', 91.750, 5.000, 270);
    Place('R60', 89.200, 7.500, 270);
    Place('R51', 90.900, 7.500, 270);
    Place('R58', 92.375, 7.500, 270);
    Place('R57', 93.675, 7.500, 270);
    Place('R56', 95.150, 7.500, 270);
    Place('R53', 96.850, 7.500, 270);
    Place('R62', 99.400, 5.000, 270);
    Place('R64', 105.350, 5.000, 270);
    Place('R66', 97.700, 5.000, 270);
    Place('R67', 103.650, 5.000, 270);
    Place('R71', 101.100, 5.000, 270);
    Place('R72', 98.550, 7.500, 270);
    Place('R63', 100.250, 7.500, 270);
    Place('R70', 101.725, 7.500, 270);
    Place('R69', 103.025, 7.500, 270);
    Place('R68', 104.500, 7.500, 270);
    Place('R65', 106.200, 7.500, 270);
    Place('R74', 108.750, 5.000, 270);
    Place('R76', 114.700, 5.000, 270);
    Place('R78', 107.050, 5.000, 270);
    Place('R79', 113.000, 5.000, 270);
    Place('R83', 110.450, 5.000, 270);
    Place('R84', 107.900, 7.500, 270);
    Place('R75', 109.600, 7.500, 270);
    Place('R82', 111.075, 7.500, 270);
    Place('R81', 112.375, 7.500, 270);
    Place('R80', 113.850, 7.500, 270);
    Place('R77', 115.550, 7.500, 270);
    Place('R86', 118.100, 5.000, 270);
    Place('R88', 124.050, 5.000, 270);
    Place('R90', 116.400, 5.000, 270);
    Place('R91', 122.350, 5.000, 270);
    Place('R95', 119.800, 5.000, 270);
    Place('R96', 117.250, 7.500, 270);
    Place('R87', 118.950, 7.500, 270);
    Place('R94', 120.425, 7.500, 270);
    Place('R93', 121.725, 7.500, 270);
    Place('R92', 123.200, 7.500, 270);
    Place('R89', 124.900, 7.500, 270);
    PCBServer.PostProcess;
    Board.ViewManager_FullUpdate;
    ShowMessage('Placed ' + IntToStr(Placed) + ' of 88 components.' + #13#10 + 'Not found: ' + Missed);
End;
