{ DQS_SkewFix.pas - generated by tools/fix_pair_skew.py; do not edit by hand.
  For each DQS pair listed below, replaces one straight piece of the shorter DRAM-side wire with
  the same piece plus 45-degree skew bump(s) of 0.3305 mm each. Nothing else is changed.
  Run: open the PcbDoc > File > Run Script > Browse to DQS_SkewFix.PrjScr > FixSkew > OK. Run once. }

Var
    Board : IPCB_Board;
    Done  : Integer;

Function IsClose(A, B : Double) : Boolean;
Begin
    Result := Abs(A - B) < 0.01;
End;

Procedure AddTrack(Net : IPCB_Net; Layer : TLayer; X1, Y1, X2, Y2 : Double);
Var
    T : IPCB_Track;
Begin
    T := PCBServer.PCBObjectFactory(eTrackObject, eNoDimension, eCreate_Default);
    T.Layer := Layer;
    T.Width := MMsToCoord(0.1);
    T.X1 := Board.XOrigin + MMsToCoord(X1);
    T.Y1 := Board.YOrigin + MMsToCoord(Y1);
    T.X2 := Board.XOrigin + MMsToCoord(X2);
    T.Y2 := Board.YOrigin + MMsToCoord(Y2);
    T.Net := Net;
    Board.AddPCBObject(T);
    PCBServer.SendMessageToRobots(Board.I_ObjectAddress, c_Broadcast, PCBM_BoardRegisteration, T.I_ObjectAddress);
End;

{ Find the track of NetName on Layer from (X1,Y1) to (X2,Y2) (either direction), remove it and
  return its net; Nil if it is not there }
Function TakeTrack(NetName : String; Layer : TLayer; X1, Y1, X2, Y2 : Double) : IPCB_Net;
Var
    Iter : IPCB_BoardIterator;
    T, F : IPCB_Track;
    AX, AY, BX, BY : Double;
Begin
    Result := Nil;
    F := Nil;
    Iter := Board.BoardIterator_Create;
    Iter.AddFilter_ObjectSet(MkSet(eTrackObject));
    Iter.AddFilter_LayerSet(MkSet(Layer));
    Iter.AddFilter_Method(eProcessAll);
    T := Iter.FirstPCBObject;
    While (T <> Nil) And (F = Nil) Do
    Begin
        If (T.Net <> Nil) And (T.Net.Name = NetName) Then
        Begin
            AX := CoordToMMs(T.X1 - Board.XOrigin); AY := CoordToMMs(T.Y1 - Board.YOrigin);
            BX := CoordToMMs(T.X2 - Board.XOrigin); BY := CoordToMMs(T.Y2 - Board.YOrigin);
            If (IsClose(AX, X1) And IsClose(AY, Y1) And IsClose(BX, X2) And IsClose(BY, Y2)) Or
               (IsClose(AX, X2) And IsClose(AY, Y2) And IsClose(BX, X1) And IsClose(BY, Y1)) Then F := T;
        End;
        T := Iter.NextPCBObject;
    End;
    Board.BoardIterator_Destroy(Iter);
    If F <> Nil Then
    Begin
        Result := F.Net;
        Board.RemovePCBObject(F);
    End;
End;

Procedure FixSkew;
Var
    N : IPCB_Net;
Begin
    Board := PCBServer.GetCurrentPCBBoard;
    If Board = Nil Then
    Begin
        ShowMessage('Open the DDR4 UDIMM PcbDoc first.');
        Exit;
    End;
    Done := 0;
    PCBServer.PreProcess;
    { DQS1: NetR22_1, 1 bump(s) }
    N := TakeTrack('NetR22_1', eMidLayer2, 19.5851, 10.2379, 22.0628, 10.2379);
    If N <> Nil Then
    Begin
        AddTrack(N, eMidLayer2, 19.5851, 10.2379, 20.5351, 10.2379);
        AddTrack(N, eMidLayer2, 20.5351, 10.2379, 20.6151, 10.3179);
        AddTrack(N, eMidLayer2, 20.6151, 10.3179, 20.6151, 10.4169);
        AddTrack(N, eMidLayer2, 20.6151, 10.4169, 20.6951, 10.4969);
        AddTrack(N, eMidLayer2, 20.6951, 10.4969, 20.9351, 10.4969);
        AddTrack(N, eMidLayer2, 20.9351, 10.4969, 21.0151, 10.4169);
        AddTrack(N, eMidLayer2, 21.0151, 10.4169, 21.0151, 10.3179);
        AddTrack(N, eMidLayer2, 21.0151, 10.3179, 21.0951, 10.2379);
        AddTrack(N, eMidLayer2, 21.0951, 10.2379, 22.0628, 10.2379);
        Done := Done + 1;
    End;
    { DQS3: NetR46_1, 1 bump(s) }
    N := TakeTrack('NetR46_1', eTopLayer, 38.8757, 9.5000, 40.9664, 9.5000);
    If N <> Nil Then
    Begin
        AddTrack(N, eTopLayer, 38.8757, 9.5000, 39.6007, 9.5000);
        AddTrack(N, eTopLayer, 39.6007, 9.5000, 39.6807, 9.5800);
        AddTrack(N, eTopLayer, 39.6807, 9.5800, 39.6807, 9.6790);
        AddTrack(N, eTopLayer, 39.6807, 9.6790, 39.7607, 9.7590);
        AddTrack(N, eTopLayer, 39.7607, 9.7590, 40.0007, 9.7590);
        AddTrack(N, eTopLayer, 40.0007, 9.7590, 40.0807, 9.6790);
        AddTrack(N, eTopLayer, 40.0807, 9.6790, 40.0807, 9.5800);
        AddTrack(N, eTopLayer, 40.0807, 9.5800, 40.1607, 9.5000);
        AddTrack(N, eTopLayer, 40.1607, 9.5000, 40.9664, 9.5000);
        Done := Done + 1;
    End;
    { DQS4: NetR58_1, 1 bump(s) }
    N := TakeTrack('NetR58_1', eTopLayer, 91.8414, 9.3000, 92.9250, 8.2164);
    If N <> Nil Then
    Begin
        AddTrack(N, eTopLayer, 91.8414, 9.3000, 92.1773, 8.9641);
        AddTrack(N, eTopLayer, 92.1773, 8.9641, 92.1773, 8.8510);
        AddTrack(N, eTopLayer, 92.1773, 8.8510, 92.1073, 8.7810);
        AddTrack(N, eTopLayer, 92.1073, 8.7810, 92.1073, 8.6678);
        AddTrack(N, eTopLayer, 92.1073, 8.6678, 92.2770, 8.4981);
        AddTrack(N, eTopLayer, 92.2770, 8.4981, 92.3901, 8.4981);
        AddTrack(N, eTopLayer, 92.3901, 8.4981, 92.4601, 8.5681);
        AddTrack(N, eTopLayer, 92.4601, 8.5681, 92.5733, 8.5681);
        AddTrack(N, eTopLayer, 92.5733, 8.5681, 92.9250, 8.2164);
        Done := Done + 1;
    End;
    { DQS5: NetR70_1, 1 bump(s) }
    N := TakeTrack('NetR70_1', eTopLayer, 101.3389, 9.3439, 102.2750, 8.4078);
    If N <> Nil Then
    Begin
        AddTrack(N, eTopLayer, 101.3389, 9.3439, 101.6041, 9.0788);
        AddTrack(N, eTopLayer, 101.6041, 9.0788, 101.6041, 8.9656);
        AddTrack(N, eTopLayer, 101.6041, 8.9656, 101.5341, 8.8956);
        AddTrack(N, eTopLayer, 101.5341, 8.8956, 101.5341, 8.7825);
        AddTrack(N, eTopLayer, 101.5341, 8.7825, 101.7038, 8.6128);
        AddTrack(N, eTopLayer, 101.7038, 8.6128, 101.8169, 8.6128);
        AddTrack(N, eTopLayer, 101.8169, 8.6128, 101.8869, 8.6828);
        AddTrack(N, eTopLayer, 101.8869, 8.6828, 102.0001, 8.6828);
        AddTrack(N, eTopLayer, 102.0001, 8.6828, 102.2750, 8.4078);
        Done := Done + 1;
    End;
    { DQS7: NetR94_1, 1 bump(s) }
    N := TakeTrack('NetR94_1', eMidLayer2, 123.0500, 9.8657, 123.0500, 11.0450);
    If N <> Nil Then
    Begin
        AddTrack(N, eMidLayer2, 123.0500, 9.8657, 123.0500, 10.1657);
        AddTrack(N, eMidLayer2, 123.0500, 10.1657, 122.9700, 10.2457);
        AddTrack(N, eMidLayer2, 122.9700, 10.2457, 122.8710, 10.2457);
        AddTrack(N, eMidLayer2, 122.8710, 10.2457, 122.7910, 10.3257);
        AddTrack(N, eMidLayer2, 122.7910, 10.3257, 122.7910, 10.5657);
        AddTrack(N, eMidLayer2, 122.7910, 10.5657, 122.8710, 10.6457);
        AddTrack(N, eMidLayer2, 122.8710, 10.6457, 122.9700, 10.6457);
        AddTrack(N, eMidLayer2, 122.9700, 10.6457, 123.0500, 10.7257);
        AddTrack(N, eMidLayer2, 123.0500, 10.7257, 123.0500, 11.0450);
        Done := Done + 1;
    End;
    PCBServer.PostProcess;
    Board.ViewManager_FullUpdate;
    ShowMessage('Skew bumps added to ' + IntToStr(Done) + ' of 5 pairs. Save the PcbDoc.');
End;
