{ DQS_SkewFix2.pas - generated by tools/fix_pair_skew.py; do not edit by hand.
  For each DQS pair listed below, replaces one straight piece of the shorter DRAM-side wire with
  the same piece plus 45-degree skew bump(s) of 0.3305 mm each. Nothing else is changed.
  Run: open the PcbDoc > File > Run Script > Browse to DQS_SkewFix2.PrjScr > FixSkew > OK. Run once. }

Var
    Board : IPCB_Board;
    Done  : Integer;

Function IsClose(A, B : Double) : Boolean;
Begin
    Result := Abs(A - B) < 0.01;
End;

Procedure AddTrack(Net : IPCB_Net; Layer : TLayer; X1, Y1, X2, Y2 : Double);
Var
    T : IPCB_Track;
Begin
    T := PCBServer.PCBObjectFactory(eTrackObject, eNoDimension, eCreate_Default);
    T.Layer := Layer;
    T.Width := MMsToCoord(0.1);
    T.X1 := Board.XOrigin + MMsToCoord(X1);
    T.Y1 := Board.YOrigin + MMsToCoord(Y1);
    T.X2 := Board.XOrigin + MMsToCoord(X2);
    T.Y2 := Board.YOrigin + MMsToCoord(Y2);
    T.Net := Net;
    Board.AddPCBObject(T);
    PCBServer.SendMessageToRobots(Board.I_ObjectAddress, c_Broadcast, PCBM_BoardRegisteration, T.I_ObjectAddress);
End;

{ Find the track of NetName on Layer from (X1,Y1) to (X2,Y2) (either direction), remove it and
  return its net; Nil if it is not there }
Function TakeTrack(NetName : String; Layer : TLayer; X1, Y1, X2, Y2 : Double) : IPCB_Net;
Var
    Iter : IPCB_BoardIterator;
    T, F : IPCB_Track;
    AX, AY, BX, BY : Double;
Begin
    Result := Nil;
    F := Nil;
    Iter := Board.BoardIterator_Create;
    Iter.AddFilter_ObjectSet(MkSet(eTrackObject));
    Iter.AddFilter_LayerSet(MkSet(Layer));
    Iter.AddFilter_Method(eProcessAll);
    T := Iter.FirstPCBObject;
    While (T <> Nil) And (F = Nil) Do
    Begin
        If (T.Net <> Nil) And (T.Net.Name = NetName) Then
        Begin
            AX := CoordToMMs(T.X1 - Board.XOrigin); AY := CoordToMMs(T.Y1 - Board.YOrigin);
            BX := CoordToMMs(T.X2 - Board.XOrigin); BY := CoordToMMs(T.Y2 - Board.YOrigin);
            If (IsClose(AX, X1) And IsClose(AY, Y1) And IsClose(BX, X2) And IsClose(BY, Y2)) Or
               (IsClose(AX, X2) And IsClose(AY, Y2) And IsClose(BX, X1) And IsClose(BY, Y1)) Then F := T;
        End;
        T := Iter.NextPCBObject;
    End;
    Board.BoardIterator_Destroy(Iter);
    If F <> Nil Then
    Begin
        Result := F.Net;
        Board.RemovePCBObject(F);
    End;
End;

Procedure FixSkew;
Var
    N : IPCB_Net;
Begin
    Board := PCBServer.GetCurrentPCBBoard;
    If Board = Nil Then
    Begin
        ShowMessage('Open the DDR4 UDIMM PcbDoc first.');
        Exit;
    End;
    Done := 0;
    PCBServer.PreProcess;
    { DQS2: NetR33_1, 2 bump(s) }
    N := TakeTrack('NetR33_1', eMidLayer2, 30.7028, 9.2250, 31.8796, 10.4018);
    If N <> Nil Then
    Begin
        AddTrack(N, eMidLayer2, 30.7028, 9.2250, 30.8266, 9.3487);
        AddTrack(N, eMidLayer2, 30.8266, 9.3487, 30.9397, 9.3487);
        AddTrack(N, eMidLayer2, 30.9397, 9.3487, 31.2009, 9.0875);
        AddTrack(N, eMidLayer2, 31.2009, 9.0875, 31.3140, 9.0875);
        AddTrack(N, eMidLayer2, 31.3140, 9.0875, 31.4838, 9.2572);
        AddTrack(N, eMidLayer2, 31.4838, 9.2572, 31.4838, 9.3704);
        AddTrack(N, eMidLayer2, 31.4838, 9.3704, 31.2225, 9.6316);
        AddTrack(N, eMidLayer2, 31.2225, 9.6316, 31.2225, 9.7447);
        AddTrack(N, eMidLayer2, 31.2225, 9.7447, 31.3640, 9.8861);
        AddTrack(N, eMidLayer2, 31.3640, 9.8861, 31.4771, 9.8861);
        AddTrack(N, eMidLayer2, 31.4771, 9.8861, 31.7383, 9.6249);
        AddTrack(N, eMidLayer2, 31.7383, 9.6249, 31.8514, 9.6249);
        AddTrack(N, eMidLayer2, 31.8514, 9.6249, 32.0212, 9.7946);
        AddTrack(N, eMidLayer2, 32.0212, 9.7946, 32.0212, 9.9078);
        AddTrack(N, eMidLayer2, 32.0212, 9.9078, 31.7599, 10.1690);
        AddTrack(N, eMidLayer2, 31.7599, 10.1690, 31.7599, 10.2821);
        AddTrack(N, eMidLayer2, 31.7599, 10.2821, 31.8796, 10.4018);
        Done := Done + 1;
    End;
    PCBServer.PostProcess;
    Board.ViewManager_FullUpdate;
    ShowMessage('Skew bumps added to ' + IntToStr(Done) + ' of 1 pairs. Save the PcbDoc.');
End;
