{ Fix_Placement.pas - generated by tools/fix_placement.py; do not edit by hand.
  Moves the components listed below back to placement_final.csv.
  Components already in place are not touched. Moving a part unroutes what is attached to it,
  so run this before routing.
  Run: open the PcbDoc > File > Run Script > Browse to Fix_Placement.PrjScr > FixPlacement > OK. }

Var
    Board : IPCB_Board;
    Done  : Integer;

Procedure Place(Designator : String; X, Y, Rot : Double);
Var
    Iter : IPCB_BoardIterator;
    C, F : IPCB_Component;
Begin
    F := Nil;
    Iter := Board.BoardIterator_Create;
    Iter.AddFilter_ObjectSet(MkSet(eComponentObject));
    Iter.AddFilter_LayerSet(AllLayers);
    Iter.AddFilter_Method(eProcessAll);
    C := Iter.FirstPCBObject;
    While (C <> Nil) And (F = Nil) Do
    Begin
        If C.Name.Text = Designator Then F := C;
        C := Iter.NextPCBObject;
    End;
    Board.BoardIterator_Destroy(Iter);
    If F = Nil Then Exit;
    PCBServer.SendMessageToRobots(F.I_ObjectAddress, c_Broadcast,
        PCBM_BeginModify, c_NoEventData);
    F.X := Board.XOrigin + MMsToCoord(X);
    F.Y := Board.YOrigin + MMsToCoord(Y);
    F.Rotation := Rot;
    PCBServer.SendMessageToRobots(F.I_ObjectAddress, c_Broadcast, PCBM_EndModify, c_NoEventData);
    Done := Done + 1;
End;

Procedure FixPlacement;
Begin
    Board := PCBServer.GetCurrentPCBBoard;
    If Board = Nil Then
    Begin
        ShowMessage('Open the DDR4 UDIMM PcbDoc first.');
        Exit;
    End;
    Done := 0;
    PCBServer.PreProcess;
    Place('R2', 6.7500, 5.0000, 270);   { was 7.800, 5.825 rot 270 - moved 1.34 mm }
    Place('R4', 12.7000, 5.0000, 270);   { was 12.525, 6.225 rot 270 - moved 1.24 mm }
    Place('R6', 5.0500, 5.0000, 270);   { was 6.275, 7.050 rot 180 - moved 2.39 mm }
    Place('R7', 11.0000, 5.0000, 270);   { was 12.875, 8.700 rot 0 - moved 4.15 mm }
    Place('R11', 8.4500, 5.0000, 270);   { was 8.825, 5.800 rot 270 - moved 0.88 mm }
    Place('R12', 5.9000, 7.5000, 270);   { was 4.250, 8.150 rot 0 - moved 1.77 mm }
    Place('R3', 7.6000, 7.5000, 270);   { was 6.275, 8.025 rot 0 - moved 1.43 mm }
    Place('R10', 9.0750, 7.5000, 270);   { was 10.600, 6.200 rot 270 - moved 2.00 mm }
    Place('R9', 10.3750, 7.5000, 270);   { was 11.550, 6.225 rot 270 - moved 1.73 mm }
    Place('R8', 11.8500, 7.5000, 270);   { was 8.800, 8.675 rot 0 - moved 3.27 mm }
    Place('R5', 13.5500, 7.5000, 270);   { was 10.125, 8.400 rot 270 - moved 3.54 mm }
    Place('C5', 14.4780, 9.5250, 90);   { was 14.275, 11.625 rot 270 - moved 2.11 mm }
    Place('R18', 14.4000, 5.0000, 270);   { was 15.050, 5.050 rot 270 - moved 0.65 mm }
    Place('R50', 90.0500, 5.0000, 270);   { was 92.725, 6.775 rot 270 - moved 3.21 mm }
    Place('R54', 88.3500, 5.0000, 270);   { was 91.925, 6.750 rot 270 - moved 3.98 mm }
    Place('R59', 91.7500, 5.0000, 270);   { was 88.350, 7.100 rot 270 - moved 4.00 mm }
    Place('R60', 89.2000, 7.5000, 270);   { was 83.275, 7.875 rot 270 - moved 5.94 mm }
    Place('R51', 90.9000, 7.5000, 270);   { was 87.025, 7.225 rot 270 - moved 3.88 mm }
    Place('R58', 92.3750, 7.5000, 270);   { was 89.600, 8.575 rot 180 - moved 2.98 mm }
    Place('R57', 93.6750, 7.5000, 270);   { was 92.425, 8.600 rot 0 - moved 1.67 mm }
    Place('C54', 4.3180, 6.6040, 90);   { was 4.250, 5.650 rot 90 - moved 0.96 mm }
    PCBServer.PostProcess;
    Board.ViewManager_FullUpdate;
    ShowMessage('Moved ' + IntToStr(Done) + ' of 21 components. Save the PcbDoc.');
End;
