{ U1_Crossers.pas - generated by tools/route_dram_side.py; do not edit by hand.
  Adds the DRAM-side routing listed below (tracks and vias). Existing copper is not changed.
  Run: open the PcbDoc > File > Run Script > Browse to U1_Crossers.PrjScr > AddRoutes > OK. Run once. }

Var
    Board : IPCB_Board;

Function FindNet(Name : String) : IPCB_Net;
Var
    Iter : IPCB_BoardIterator;
    N : IPCB_Net;
Begin
    Result := Nil;
    Iter := Board.BoardIterator_Create;
    Iter.AddFilter_ObjectSet(MkSet(eNetObject));
    Iter.AddFilter_LayerSet(AllLayers);
    Iter.AddFilter_Method(eProcessAll);
    N := Iter.FirstPCBObject;
    While (N <> Nil) And (Result = Nil) Do
    Begin
        If N.Name = Name Then Result := N;
        N := Iter.NextPCBObject;
    End;
    Board.BoardIterator_Destroy(Iter);
End;

Procedure AddTrack(Net : IPCB_Net; Layer : TLayer; X1, Y1, X2, Y2 : Double);
Var
    T : IPCB_Track;
Begin
    T := PCBServer.PCBObjectFactory(eTrackObject, eNoDimension, eCreate_Default);
    T.Layer := Layer;
    T.Width := MMsToCoord(0.1);
    T.X1 := Board.XOrigin + MMsToCoord(X1);
    T.Y1 := Board.YOrigin + MMsToCoord(Y1);
    T.X2 := Board.XOrigin + MMsToCoord(X2);
    T.Y2 := Board.YOrigin + MMsToCoord(Y2);
    T.Net := Net;
    Board.AddPCBObject(T);
    PCBServer.SendMessageToRobots(Board.I_ObjectAddress, c_Broadcast, PCBM_BoardRegisteration, T.I_ObjectAddress);
End;

Procedure AddVia(Net : IPCB_Net; X, Y : Double);
Var
    V : IPCB_Via;
Begin
    V := PCBServer.PCBObjectFactory(eViaObject, eNoDimension, eCreate_Default);
    V.X := Board.XOrigin + MMsToCoord(X);
    V.Y := Board.YOrigin + MMsToCoord(Y);
    V.Size := MMsToCoord(0.4);
    V.HoleSize := MMsToCoord(0.2);
    V.LowLayer := eTopLayer;
    V.HighLayer := eBottomLayer;
    V.Net := Net;
    Board.AddPCBObject(V);
    PCBServer.SendMessageToRobots(Board.I_ObjectAddress, c_Broadcast, PCBM_BoardRegisteration, V.I_ObjectAddress);
End;

Procedure AddRoutes;
Var
    N : IPCB_Net;
Begin
    Board := PCBServer.GetCurrentPCBBoard;
    If Board = Nil Then
    Begin
        ShowMessage('Open the DDR4 UDIMM PcbDoc first.');
        Exit;
    End;
    PCBServer.PreProcess;
    { NetR2_1 (R2 pad 1 -> U1-C2) L1 + L8, 8.86 mm: 8.86 mm }
    N := FindNet('NetR2_1');
    If N = Nil Then ShowMessage('Net NetR2_1 not found.') Else
    Begin
        AddTrack(N, eTopLayer, 6.750, 5.375, 7.300, 5.375);
        AddTrack(N, eTopLayer, 7.300, 5.375, 8.075, 6.150);
        AddTrack(N, eBottomLayer, 8.075, 6.150, 12.100, 10.175);
        AddTrack(N, eBottomLayer, 12.100, 10.175, 12.100, 11.700);
        AddVia(N, 8.075, 6.150);
    End;
    { NetR6_1 (R6 pad 1 -> U1-D2) L1 + L8, 10.46 mm: 10.46 mm }
    N := FindNet('NetR6_1');
    If N = Nil Then ShowMessage('Net NetR6_1 not found.') Else
    Begin
        AddTrack(N, eTopLayer, 5.050, 5.375, 5.125, 5.450);
        AddTrack(N, eTopLayer, 5.125, 5.450, 5.125, 6.225);
        AddTrack(N, eBottomLayer, 5.125, 6.225, 11.025, 12.125);
        AddTrack(N, eBottomLayer, 11.025, 12.125, 11.725, 12.125);
        AddTrack(N, eBottomLayer, 11.725, 12.125, 12.100, 12.500);
        AddVia(N, 5.125, 6.225);
    End;
    { NetR8_1 (R8 pad 1 -> U1-E7) L1 + L3, 8.42 mm: 8.42 mm }
    N := FindNet('NetR8_1');
    If N = Nil Then ShowMessage('Net NetR8_1 not found.') Else
    Begin
        AddTrack(N, eTopLayer, 11.850, 7.875, 11.850, 8.125);
        AddTrack(N, eTopLayer, 11.850, 8.125, 11.375, 8.600);
        AddTrack(N, eMidLayer2, 11.375, 8.600, 9.475, 8.600);
        AddTrack(N, eMidLayer2, 9.475, 8.600, 7.675, 10.400);
        AddTrack(N, eMidLayer2, 7.675, 10.400, 7.675, 12.925);
        AddTrack(N, eMidLayer2, 7.675, 12.925, 7.300, 13.300);
        AddVia(N, 11.375, 8.600);
    End;
    { NetR5_1 (R5 pad 1 -> U1-D7) L1 + L8, 10.64 mm: 10.64 mm }
    N := FindNet('NetR5_1');
    If N = Nil Then ShowMessage('Net NetR5_1 not found.') Else
    Begin
        AddTrack(N, eTopLayer, 13.550, 7.875, 13.550, 8.600);
        AddTrack(N, eBottomLayer, 13.550, 8.600, 13.550, 11.575);
        AddTrack(N, eBottomLayer, 13.550, 11.575, 12.250, 12.875);
        AddTrack(N, eBottomLayer, 12.250, 12.875, 7.675, 12.875);
        AddTrack(N, eBottomLayer, 7.675, 12.875, 7.300, 12.500);
        AddVia(N, 13.550, 8.600);
    End;
    PCBServer.PostProcess;
    Board.ViewManager_FullUpdate;
    ShowMessage('Added the DRAM-side routing of 4 nets. Save the PcbDoc.');
End;
