{ U2_Route.pas - generated by tools/route_dram_side.py; do not edit by hand.
  Adds the DRAM-side routing listed below (tracks and vias). Existing copper is not changed.
  Run: open the PcbDoc > File > Run Script > Browse to U2_Route.PrjScr > AddRoutes > OK. Run once. }

Var
    Board : IPCB_Board;

Function FindNet(Name : String) : IPCB_Net;
Var
    Iter : IPCB_BoardIterator;
    N : IPCB_Net;
Begin
    Result := Nil;
    Iter := Board.BoardIterator_Create;
    Iter.AddFilter_ObjectSet(MkSet(eNetObject));
    Iter.AddFilter_LayerSet(AllLayers);
    Iter.AddFilter_Method(eProcessAll);
    N := Iter.FirstPCBObject;
    While (N <> Nil) And (Result = Nil) Do
    Begin
        If N.Name = Name Then Result := N;
        N := Iter.NextPCBObject;
    End;
    Board.BoardIterator_Destroy(Iter);
End;

Procedure AddTrack(Net : IPCB_Net; Layer : TLayer; X1, Y1, X2, Y2 : Double);
Var
    T : IPCB_Track;
Begin
    T := PCBServer.PCBObjectFactory(eTrackObject, eNoDimension, eCreate_Default);
    T.Layer := Layer;
    T.Width := MMsToCoord(0.1);
    T.X1 := Board.XOrigin + MMsToCoord(X1);
    T.Y1 := Board.YOrigin + MMsToCoord(Y1);
    T.X2 := Board.XOrigin + MMsToCoord(X2);
    T.Y2 := Board.YOrigin + MMsToCoord(Y2);
    T.Net := Net;
    Board.AddPCBObject(T);
    PCBServer.SendMessageToRobots(Board.I_ObjectAddress, c_Broadcast, PCBM_BoardRegisteration, T.I_ObjectAddress);
End;

Procedure AddVia(Net : IPCB_Net; X, Y : Double);
Var
    V : IPCB_Via;
Begin
    V := PCBServer.PCBObjectFactory(eViaObject, eNoDimension, eCreate_Default);
    V.X := Board.XOrigin + MMsToCoord(X);
    V.Y := Board.YOrigin + MMsToCoord(Y);
    V.Size := MMsToCoord(0.4);
    V.HoleSize := MMsToCoord(0.2);
    V.LowLayer := eTopLayer;
    V.HighLayer := eBottomLayer;
    V.Net := Net;
    Board.AddPCBObject(V);
    PCBServer.SendMessageToRobots(Board.I_ObjectAddress, c_Broadcast, PCBM_BoardRegisteration, V.I_ObjectAddress);
End;

Procedure AddRoutes;
Var
    N : IPCB_Net;
Begin
    Board := PCBServer.GetCurrentPCBBoard;
    If Board = Nil Then
    Begin
        ShowMessage('Open the DDR4 UDIMM PcbDoc first.');
        Exit;
    End;
    PCBServer.PreProcess;
    { R18 DQ12 (R18 pad 1 -> U2-D2) L1 + L8, 11.83 mm: 11.83 mm }
    N := FindNet('NetR18_1');
    If N = Nil Then ShowMessage('Net NetR18_1 not found.') Else
    Begin
        AddTrack(N, eTopLayer, 14.400, 5.375, 14.800, 5.375);
        AddTrack(N, eTopLayer, 14.800, 5.375, 16.200, 6.775);
        AddTrack(N, eBottomLayer, 16.200, 6.775, 16.200, 7.200);
        AddTrack(N, eBottomLayer, 16.200, 7.200, 21.125, 12.125);
        AddTrack(N, eBottomLayer, 21.125, 12.125, 22.650, 12.125);
        AddTrack(N, eBottomLayer, 22.650, 12.125, 23.025, 12.500);
        AddVia(N, 16.200, 6.775);
    End;
    { R14 DQ8 (R14 pad 1 -> U2-C2) L1 + L8, 9.74 mm: 9.74 mm }
    N := FindNet('NetR14_1');
    If N = Nil Then ShowMessage('Net NetR14_1 not found.') Else
    Begin
        AddTrack(N, eTopLayer, 16.100, 5.375, 16.500, 5.375);
        AddTrack(N, eTopLayer, 16.500, 5.375, 17.725, 6.600);
        AddTrack(N, eBottomLayer, 17.725, 6.600, 17.725, 6.925);
        AddTrack(N, eBottomLayer, 17.725, 6.925, 22.125, 11.325);
        AddTrack(N, eBottomLayer, 22.125, 11.325, 22.650, 11.325);
        AddTrack(N, eBottomLayer, 22.650, 11.325, 23.025, 11.700);
        AddVia(N, 17.725, 6.600);
    End;
    { R19 DQ14 (R19 pad 1 -> U2-E3) L1 + L3, 8.70 mm: 8.70 mm }
    N := FindNet('NetR19_1');
    If N = Nil Then ShowMessage('Net NetR19_1 not found.') Else
    Begin
        AddTrack(N, eTopLayer, 20.350, 5.375, 20.350, 10.675);
        AddTrack(N, eMidLayer2, 20.350, 10.675, 20.350, 11.425);
        AddTrack(N, eMidLayer2, 20.350, 11.425, 22.225, 13.300);
        AddVia(N, 20.350, 10.675);
    End;
    { R16 DQ10 (R16 pad 1 -> U2-D3) L1 + L3, 7.82 mm: 7.82 mm }
    N := FindNet('NetR16_1');
    If N = Nil Then ShowMessage('Net NetR16_1 not found.') Else
    Begin
        AddTrack(N, eTopLayer, 22.050, 5.375, 22.050, 7.750);
        AddTrack(N, eTopLayer, 22.050, 7.750, 21.350, 8.450);
        AddTrack(N, eTopLayer, 21.350, 8.450, 21.350, 11.700);
        AddTrack(N, eMidLayer2, 21.350, 11.700, 21.425, 11.700);
        AddTrack(N, eMidLayer2, 21.425, 11.700, 22.225, 12.500);
        AddVia(N, 21.350, 11.700);
    End;
    { R17 DQ11 (R17 pad 1 -> U2-D7) L1 + L3, 8.65 mm: 8.65 mm }
    N := FindNet('NetR17_1');
    If N = Nil Then ShowMessage('Net NetR17_1 not found.') Else
    Begin
        AddTrack(N, eTopLayer, 22.900, 7.875, 21.900, 8.875);
        AddTrack(N, eMidLayer2, 21.900, 8.875, 18.625, 8.875);
        AddTrack(N, eMidLayer2, 18.625, 8.875, 18.400, 9.100);
        AddTrack(N, eMidLayer2, 18.400, 9.100, 18.400, 9.750);
        AddTrack(N, eMidLayer2, 18.400, 9.750, 18.600, 9.950);
        AddTrack(N, eMidLayer2, 18.600, 9.950, 18.600, 12.125);
        AddTrack(N, eMidLayer2, 18.600, 12.125, 18.225, 12.500);
        AddVia(N, 21.900, 8.875);
    End;
    { R20 DQ15 (R20 pad 1 -> U2-E7) L1 + L8, 6.80 mm: 6.80 mm }
    N := FindNet('NetR20_1');
    If N = Nil Then ShowMessage('Net NetR20_1 not found.') Else
    Begin
        AddTrack(N, eTopLayer, 21.200, 7.875, 20.725, 8.350);
        AddTrack(N, eTopLayer, 20.725, 8.350, 20.725, 11.050);
        AddTrack(N, eTopLayer, 20.725, 11.050, 20.075, 11.700);
        AddTrack(N, eBottomLayer, 20.075, 11.700, 18.475, 13.300);
        AddTrack(N, eBottomLayer, 18.475, 13.300, 18.225, 13.300);
        AddVia(N, 20.075, 11.700);
    End;
    { R23 DM1 (R23 pad 1 -> U2-A7) L1 + L3, 5.40 mm: 5.40 mm }
    N := FindNet('NetR23_1');
    If N = Nil Then ShowMessage('Net NetR23_1 not found.') Else
    Begin
        AddTrack(N, eTopLayer, 17.800, 5.375, 17.800, 6.050);
        AddTrack(N, eTopLayer, 17.800, 6.050, 17.850, 6.100);
        AddTrack(N, eMidLayer2, 17.850, 6.100, 17.700, 6.100);
        AddTrack(N, eMidLayer2, 17.700, 6.100, 17.350, 6.450);
        AddTrack(N, eMidLayer2, 17.350, 6.450, 17.350, 9.225);
        AddTrack(N, eMidLayer2, 17.350, 9.225, 18.225, 10.100);
        AddVia(N, 17.850, 6.100);
    End;
    { R15 DQ9 (R15 pad 1 -> U2-B7) L1 + L8, 3.55 mm: 3.55 mm }
    N := FindNet('NetR15_1');
    If N = Nil Then ShowMessage('Net NetR15_1 not found.') Else
    Begin
        AddTrack(N, eTopLayer, 16.950, 7.875, 16.950, 8.900);
        AddTrack(N, eBottomLayer, 16.950, 8.900, 17.850, 9.800);
        AddTrack(N, eBottomLayer, 17.850, 9.800, 17.850, 10.525);
        AddTrack(N, eBottomLayer, 17.850, 10.525, 18.225, 10.900);
        AddVia(N, 16.950, 8.900);
    End;
    PCBServer.PostProcess;
    Board.ViewManager_FullUpdate;
    ShowMessage('Added the DRAM-side routing of 8 nets. Save the PcbDoc.');
End;
