"""Equalise DQS pair halves on the DRAM side by adding 45-degree skew bumps to the shorter wire.

For every DQS pair k (DRAM side: NetR(12k+9)_1 = DQS_t, NetR(12k+10)_1 = DQS_c) whose halves differ by
more than 0.1 mm (main spec Table 11), this finds a straight piece of the shorter wire (on L1 or L3,
any 0/45/90 degree direction, at least 0.76 mm long) where a bump fits on the side away from its
partner, checks every point of the new shape against all other copper (the 0.10 mm board rule,
which the coupled pairs already run at), and writes an Altium script that swaps that piece for the same
piece with the bump. One bump adds 0.3305 mm; several are used if needed (up to 3).

Usage:
    py -3.11 tools/fix_pair_skew.py <board.PcbDoc> [script name]     (default DQS_SkewFix)
"""
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import route_dram_side as R                      # noqa: E402

# Bump shape in local coordinates (u along the piece, v away from the partner), centred on u = 0.
# The height h is solved from the length needed: a bump of height h adds 2h - 0.1875 mm, so
# h = (gain + 0.1875) / 2. Corners stay at 45 degrees at every height.
BASE = 0.56                   # footprint of one bump along the wire
PITCH = 0.76                  # bump centre to bump centre


def bump(h):
    return [(-0.28, 0.0), (-0.20, 0.08), (-0.20, h - 0.08), (-0.12, h),
            (0.12, h), (0.20, h - 0.08), (0.20, 0.08), (0.28, 0.0)]


def height_for(gain):
    return (gain + 0.1875) / 2.0


LAYER_NAME = {1: "L1", 3: "L3"}


def length(tracks, net):
    return sum(math.dist(a, b) for n, _, a, b, _ in tracks if n == net)


def shape(a, b, centres, side, h):
    """Polyline from a to b with bumps of height h centred at distances `centres` along the piece."""
    L = math.dist(a, b)
    ux, uy = (b[0] - a[0]) / L, (b[1] - a[1]) / L
    vx, vy = -uy * side, ux * side
    pts = [a]
    for c in centres:
        for du, dv in bump(h):
            u = c + du
            pts.append((a[0] + ux * u + vx * dv, a[1] + uy * u + vy * dv))
    pts.append(b)
    return pts


def fits(board, net, pts, layer):
    for p, q in zip(pts, pts[1:]):
        steps = max(1, int(math.dist(p, q) / 0.02))
        for i in range(steps + 1):
            x = (p[0] + (q[0] - p[0]) * i / steps, p[1] + (q[1] - p[1]) * i / steps)
            if not board.clear_on(x, layer, net, R.WIDTH / 2):
                return False
    return True


SKEW_CLEAR = 0.0999          # the board rule (0.10 mm edge to edge); pairs already run at exactly 0.10


def plan(path):
    R.CLEAR = SKEW_CLEAR
    tracks, vias, pads = R.streams(path)
    board = R.Board(tracks, vias, pads)
    fixes = []
    for k in range(8):
        t, c = f"NetR{12 * k + 9}_1", f"NetR{12 * k + 10}_1"
        lt, lc = length(tracks, t), length(tracks, c)
        diff = abs(lt - lc)
        if lt < 0.6 or lc < 0.6:
            print(f"DQS{k}: DRAM side not routed")
            continue
        if diff <= 0.1:
            print(f"DQS{k}: halves {lt:.3f} / {lc:.3f} mm - already matched")
            continue
        short = c if lc < lt else t
        partner = t if short == c else c
        done = False
        # try the fewest, shortest bumps first: n bumps each adding diff/n
        for n in range(1, 9):
            h = height_for(diff / n)
            if h < 0.12 or h > 0.60:              # too flat to draw, or too tall to fit beside a pair
                continue
            span = BASE * n + 0.2 * (n - 1)
            for seg in sorted((s for s in tracks if s[0] == short and s[1] in LAYER_NAME),
                              key=lambda s: -math.dist(s[2], s[3])):
                _, lay, a, b, _ = seg
                L = math.dist(a, b)
                if L < span + 0.2:
                    continue
                starts = [0.1 + i * 0.025 for i in range(int((L - span - 0.2) / 0.025) + 1)]
                starts.sort(key=lambda u: abs(u - (L - span) / 2))
                for first, side in ((u + 0.28, sd) for u in starts for sd in (1, -1)):
                    centres = [first + i * PITCH for i in range(n)]
                    pts = shape(a, b, centres, side, h)
                    if fits(board, short, pts, LAYER_NAME[lay]):
                        fixes.append((k, short, lay, a, b, pts, n))
                        print(f"DQS{k}: {short} {min(lt, lc):.3f} -> +{diff:.3f} mm on {LAYER_NAME[lay]} "
                              f"({a[0]:.3f},{a[1]:.3f})-({b[0]:.3f},{b[1]:.3f}), "
                              f"{n} bump(s) {h:.3f} mm tall, partner {partner}")
                        done = True
                        break
                if done:
                    break
            if done:
                break
        if not done:
            print(f"DQS{k}: halves {lt:.3f} / {lc:.3f}, difference {diff:.3f} - no room on {short}, re-route")
    return fixes


def pas(name, fixes):
    L = [f"{{ {name}.pas - generated by tools/fix_pair_skew.py; do not edit by hand.",
         "  For each DQS pair listed below, replaces one straight piece of the shorter DRAM-side wire with",
         "  the same piece plus 45-degree skew bump(s) of 0.3305 mm each. Nothing else is changed.",
         f"  Run: open the PcbDoc > File > Run Script > Browse to {name}.PrjScr > FixSkew > OK. Run once. }}",
         "", "Var", "    Board : IPCB_Board;", "    Done  : Integer;", "",
         "Function IsClose(A, B : Double) : Boolean;", "Begin", "    Result := Abs(A - B) < 0.01;", "End;", "",
         "Procedure AddTrack(Net : IPCB_Net; Layer : TLayer; X1, Y1, X2, Y2 : Double);",
         "Var", "    T : IPCB_Track;", "Begin",
         "    T := PCBServer.PCBObjectFactory(eTrackObject, eNoDimension, eCreate_Default);",
         "    T.Layer := Layer;", f"    T.Width := MMsToCoord({R.WIDTH});",
         "    T.X1 := Board.XOrigin + MMsToCoord(X1);", "    T.Y1 := Board.YOrigin + MMsToCoord(Y1);",
         "    T.X2 := Board.XOrigin + MMsToCoord(X2);", "    T.Y2 := Board.YOrigin + MMsToCoord(Y2);",
         "    T.Net := Net;", "    Board.AddPCBObject(T);",
         "    PCBServer.SendMessageToRobots(Board.I_ObjectAddress, c_Broadcast, PCBM_BoardRegisteration, T.I_ObjectAddress);",
         "End;", "",
         "{ Find the track of NetName on Layer from (X1,Y1) to (X2,Y2) (either direction), remove it and",
         "  return its net; Nil if it is not there }",
         "Function TakeTrack(NetName : String; Layer : TLayer; X1, Y1, X2, Y2 : Double) : IPCB_Net;",
         "Var", "    Iter : IPCB_BoardIterator;", "    T, F : IPCB_Track;", "    AX, AY, BX, BY : Double;", "Begin",
         "    Result := Nil;", "    F := Nil;", "    Iter := Board.BoardIterator_Create;",
         "    Iter.AddFilter_ObjectSet(MkSet(eTrackObject));", "    Iter.AddFilter_LayerSet(MkSet(Layer));",
         "    Iter.AddFilter_Method(eProcessAll);", "    T := Iter.FirstPCBObject;",
         "    While (T <> Nil) And (F = Nil) Do", "    Begin",
         "        If (T.Net <> Nil) And (T.Net.Name = NetName) Then", "        Begin",
         "            AX := CoordToMMs(T.X1 - Board.XOrigin); AY := CoordToMMs(T.Y1 - Board.YOrigin);",
         "            BX := CoordToMMs(T.X2 - Board.XOrigin); BY := CoordToMMs(T.Y2 - Board.YOrigin);",
         "            If (IsClose(AX, X1) And IsClose(AY, Y1) And IsClose(BX, X2) And IsClose(BY, Y2)) Or",
         "               (IsClose(AX, X2) And IsClose(AY, Y2) And IsClose(BX, X1) And IsClose(BY, Y1)) Then F := T;",
         "        End;", "        T := Iter.NextPCBObject;", "    End;", "    Board.BoardIterator_Destroy(Iter);",
         "    If F <> Nil Then", "    Begin", "        Result := F.Net;", "        Board.RemovePCBObject(F);", "    End;",
         "End;", "",
         "Procedure FixSkew;", "Var", "    N : IPCB_Net;", "Begin",
         "    Board := PCBServer.GetCurrentPCBBoard;",
         "    If Board = Nil Then", "    Begin", "        ShowMessage('Open the DDR4 UDIMM PcbDoc first.');",
         "        Exit;", "    End;", "    Done := 0;", "    PCBServer.PreProcess;"]
    for k, net, lay, a, b, pts, n in fixes:
        pl = "eTopLayer" if lay == 1 else "eMidLayer2"
        L += [f"    {{ DQS{k}: {net}, {n} bump(s) }}",
              f"    N := TakeTrack('{net}', {pl}, {a[0]:.4f}, {a[1]:.4f}, {b[0]:.4f}, {b[1]:.4f});",
              "    If N <> Nil Then", "    Begin"]
        for p, q in zip(pts, pts[1:]):
            L.append(f"        AddTrack(N, {pl}, {p[0]:.4f}, {p[1]:.4f}, {q[0]:.4f}, {q[1]:.4f});")
        L += ["        Done := Done + 1;", "    End;"]
    L += ["    PCBServer.PostProcess;", "    Board.ViewManager_FullUpdate;",
          f"    ShowMessage('Skew bumps added to ' + IntToStr(Done) + ' of {len(fixes)} pairs. Save the PcbDoc.');",
          "End;", ""]
    return "\r\n".join(L)


def main():
    if len(sys.argv) not in (2, 3):
        sys.exit(__doc__)
    name = sys.argv[2] if len(sys.argv) == 3 else "DQS_SkewFix"
    fixes = plan(sys.argv[1])
    if not fixes:
        return
    root = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
    out = os.path.join(root, "hardware", "scripts")
    with open(os.path.join(out, name + ".pas"), "w", newline="", encoding="ascii") as fh:
        fh.write(pas(name, fixes))
    with open(os.path.join(out, name + ".PrjScr"), "w", newline="", encoding="ascii") as fh:
        fh.write("\r\n".join(["[Design]", "Version=1.0", "HierarchyMode=0", "OpenOutputs=1", "ArchiveProject=0",
                              "TimestampOutput=0", "SeparateFolders=0", "", "[Preferences]", "PrefsVaultGUID=",
                              "PrefsRevisionGUID=", "", "[Document1]", f"DocumentPath={name}.pas",
                              "AnnotationEnabled=1", "AnnotateStartValue=1", "AnnotationIndexControlEnabled=0",
                              "AnnotateSuffix=", "AnnotateScope=All", "AnnotateOrder=-1", "DoLibraryUpdate=1",
                              "DoDatabaseUpdate=1", "DItemRevisionGUID=", "GenerateClassCluster=0",
                              "DocumentUniqueId=", ""]))
    print(f"wrote hardware/scripts/{name}.pas and .PrjScr ({len(fixes)} pairs)")


if __name__ == "__main__":
    main()
