"""Write an Altium script that moves every component back to the recorded placement.

Compares the saved PcbDoc against hardware/placement_final.csv (or the plan with --plan) and emits
one script that sets the X, Y and rotation of each part that has drifted. Parts already in place are
left alone. Moving a component in Altium unroutes whatever was attached to it, so run this before
routing, not after.

Usage:
    py -3.11 tools/fix_placement.py <board.PcbDoc> [script name] [--plan] [--tol 0.01]
"""
import csv
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import check_placement as CP                      # noqa: E402

PRJSCR = ["[Design]", "Version=1.0", "HierarchyMode=0", "OpenOutputs=1", "ArchiveProject=0",
          "TimestampOutput=0", "SeparateFolders=0", "", "[Preferences]", "PrefsVaultGUID=",
          "PrefsRevisionGUID=", "", "[Document1]", "DocumentPath=%s.pas", "AnnotationEnabled=1",
          "AnnotateStartValue=1", "AnnotationIndexControlEnabled=0", "AnnotateSuffix=", "AnnotateScope=All",
          "AnnotateOrder=-1", "DoLibraryUpdate=1", "DoDatabaseUpdate=1", "DItemRevisionGUID=",
          "GenerateClassCluster=0", "DocumentUniqueId=", ""]


def pas(name, moves, source):
    L = ["{ %s.pas - generated by tools/fix_placement.py; do not edit by hand." % name,
         "  Moves the components listed below back to %s." % source,
         "  Components already in place are not touched. Moving a part unroutes what is attached to it,",
         "  so run this before routing.",
         "  Run: open the PcbDoc > File > Run Script > Browse to %s.PrjScr > FixPlacement > OK. }" % name,
         "", "Var", "    Board : IPCB_Board;", "    Done  : Integer;", "",
         "Procedure Place(Designator : String; X, Y, Rot : Double);",
         "Var", "    Iter : IPCB_BoardIterator;", "    C, F : IPCB_Component;", "Begin",
         "    F := Nil;", "    Iter := Board.BoardIterator_Create;",
         "    Iter.AddFilter_ObjectSet(MkSet(eComponentObject));", "    Iter.AddFilter_LayerSet(AllLayers);",
         "    Iter.AddFilter_Method(eProcessAll);", "    C := Iter.FirstPCBObject;",
         "    While (C <> Nil) And (F = Nil) Do", "    Begin",
         "        If C.Name.Text = Designator Then F := C;", "        C := Iter.NextPCBObject;", "    End;",
         "    Board.BoardIterator_Destroy(Iter);",
         "    If F = Nil Then Exit;", "    PCBServer.SendMessageToRobots(F.I_ObjectAddress, c_Broadcast,",
         "        PCBM_BeginModify, c_NoEventData);",
         "    F.X := Board.XOrigin + MMsToCoord(X);", "    F.Y := Board.YOrigin + MMsToCoord(Y);",
         "    F.Rotation := Rot;",
         "    PCBServer.SendMessageToRobots(F.I_ObjectAddress, c_Broadcast, PCBM_EndModify, c_NoEventData);",
         "    Done := Done + 1;", "End;", "",
         "Procedure FixPlacement;", "Begin", "    Board := PCBServer.GetCurrentPCBBoard;",
         "    If Board = Nil Then", "    Begin", "        ShowMessage('Open the DDR4 UDIMM PcbDoc first.');",
         "        Exit;", "    End;", "    Done := 0;", "    PCBServer.PreProcess;"]
    for des, (x, y, rot), (hx, hy, hrot), moved in moves:
        L.append("    Place('%s', %.4f, %.4f, %g);   { was %.3f, %.3f rot %g - moved %.2f mm }"
                 % (des, x, y, rot, hx, hy, hrot, moved))
    L += ["    PCBServer.PostProcess;", "    Board.ViewManager_FullUpdate;",
          "    ShowMessage('Moved ' + IntToStr(Done) + ' of %d components. Save the PcbDoc.');" % len(moves),
          "End;", ""]
    return "\r\n".join(L)


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if not args:
        sys.exit(__doc__)
    path = args[0]
    name = args[1] if len(args) > 1 else "Fix_Placement"
    tol = float(sys.argv[sys.argv.index("--tol") + 1]) if "--tol" in sys.argv else 0.01
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    csv_name = "placement.csv" if "--plan" in sys.argv else "placement_final.csv"
    ref = os.path.join(root, "hardware", csv_name)
    with open(ref, newline="", encoding="utf-8") as fh:
        plan = list(csv.DictReader(fh))
    have = CP.components(path)

    moves = []
    for row in plan:
        des = row["designator"]
        if des not in have:
            print("missing from the board: %s" % des)
            continue
        x, y, rot = float(row["x_mm"]), float(row["y_mm"]), float(row["rotation"]) % 360
        hx, hy, hrot, _lay = have[des]
        moved = ((hx - x) ** 2 + (hy - y) ** 2) ** 0.5
        if moved > tol or abs(hrot - rot) > 0.5:
            moves.append((des, (x, y, rot), (hx, hy, hrot), moved))

    if not moves:
        print("every component matches %s - nothing to do" % csv_name)
        return
    print("%d components to move back to %s:" % (len(moves), csv_name))
    for des, (x, y, rot), (hx, hy, hrot), moved in sorted(moves, key=lambda m: -m[3]):
        print("  %-5s (%7.3f, %6.3f) rot %-3g  <-  (%7.3f, %6.3f) rot %-3g   %.2f mm"
              % (des, x, y, rot, hx, hy, hrot, moved))
    out = os.path.join(root, "hardware", "scripts")
    with open(os.path.join(out, name + ".pas"), "w", newline="", encoding="ascii") as fh:
        fh.write(pas(name, moves, csv_name))
    with open(os.path.join(out, name + ".PrjScr"), "w", newline="", encoding="ascii") as fh:
        fh.write("\r\n".join(line % name if "%s" in line else line for line in PRJSCR))
    print("\nwrote hardware/scripts/%s.pas and .PrjScr" % name)


if __name__ == "__main__":
    main()
